'use strict';
var Helper, chai, expect, helper;

Helper = require('hubot-test-helper');

chai = require('chai');

expect = chai.expect;

helper = new Helper('../src/asynchronous-test.coffee');

describe('asynchronous-test', function() {
  beforeEach(function() {
    return this.room = helper.createRoom();
  });
  afterEach(function() {
    return this.room.destroy();
  });
  it('responds to hello', function() {
    return this.room.user.say('alice', '@hubot hello').then((function(_this) {
      return function() {
        return expect(_this.room.messages).to.eql([['alice', '@hubot hello'], ['hubot', '@alice hello!']]);
      };
    })(this));
  });
  return it('hears orly', function() {
    return this.room.user.say('bob', 'just wanted to say orly').then((function(_this) {
      return function() {
        return expect(_this.room.messages).to.eql([['bob', 'just wanted to say orly'], ['hubot', 'yarly']]);
      };
    })(this));
  });


});

// ---
// generated by coffee-script 1.9.2
