'use strict';
var Helper, Promise, co, expect, helper;

Helper = require('hubot-test-helper');

helper = new Helper('../src/webshot.js');

Promise = require('bluebird');

co = require('co');

expect = require('chai').expect;

describe('webshot', function() {
  beforeEach(function () {
    return this.room = helper.createRoom({
      httpd: false
    });
  });
  describe('webshot context', function() {
    this.timeout(10000);
    co(function *(_this){
      yield _this.room.user.say('user1', 'webshot');
    });
    it('webshot', function() {
      return this.room.user.say('user1', 'webshot').then(function() {
        console.log('hogehoge');
      });
    });
  });
});

// ---
// generated by coffee-script 1.9.2
